### PR TITLE
I added custom regions to the front page.

### PR DESCRIPTION
**Pull request by deetergp**
Let me know when you pull the code and I will log in to the live site and create the necessary blocks.

### CODE REVIEW

**Comment by shrop** [comment]
Are you going to put the current html in blocks, so the home page effectively looks the same? That will help me with styling the new events view. Thanks!

**Comment by deetergp** [comment]
Mark,

That is the plan. The "blurb" region on the left will contain a created block. And the right-hand events list will be a views block. Does that work for you?

-Scott

**Comment by shrop** [comment]
yeah, but just drop the current html in a block for the right for now as we solidify the view and fields related. That is a moving target now. I just want to make sure we have that look to grab the styles from easily :)

**Comment by deetergp** [comment]
You got it!

-=SD=-

**Comment by shrop** [comment]
Cool..I am good if you style it, but we have to figure out the time grouping which may change the date/time fields and require reimports of everything :)

**Comment by deetergp** [comment]
No sweat! I'll be ready to re-address styling when we get the view sorted out.

-=SD=-

**Pull request merged**
